guild_id: 1460995865329270964

role_management:
  staff_roles:
    - owner
    - co_owner
    - admin
    - moderator
    - dev 
    
  allowed_roles:
    - supporter
    - member_1
    - member_2
    - member_3
    - member_4

roles:
  bot: 1461009559048032361
  owner: 1460995865731793089
  co_owner: 1460995865731793088
  admin: 1460995865731793086
  moderator: 1460995865731793085
  dev: 1464688329491484792
  supporter: 1460995865731793084
  member_1: 1460995865329270968 # Pro-Gamer
  member_2: 1460995865329270969 # Epic-Gamer
  member_3: 1460995865329270970 # Legendary-Gamer
  member_4: 1460995865329270971 #Godly-Gamer

log_channels:
  bot: 1460995867334017169
  moderation: 1461013968335409388

permissions:
  warn:
    min_level: MOD
  warnings:
    min_level: SUPPORT
  del_warnings:
    min_level: ADMIN
  timeout:
    min_level: MOD
  untimeout:
    min_level: MOD
  clear:
    min_level: MOD
  kick:
    min_level: ADMIN
  ban:
    min_level: ADMIN
  unban:
    min_level: ADMIN
  userinfo:
    min_level: SUPPORT
  devpanel:
    min_level: DEV
  reload:
    min_level: DEV
  role_add:
    min_level: MOD
  role_remove:
    min_level: MOD
  clear:
    min_level: MOD  

security:
  lock_owner_actions: true
  admin_is_owner: false
  owner_role_only: true

moderation:
  warn_kick_threshold: 3
  warn_ban_threshold: 5
  warn_timeout_threshold: 2
  warn_timeout_duration: 300 # in seconds