guild_id: 1460995865329270964

roles:
  bot: 1461009559048032361
  admin: 1460995865731793089
  moderator: 1460995865731793085
  member: 1460995865329270968

log_channels:
  bot: 1460995867334017169
  moderation: 1461013968335409388


  moderation:
    warn_kick_threshold: 3
    warn_ban_threshold: 5
    warn_timeout_threshold: 2
    warn_timeout_duration: 300 # in seconds
