guild_id: 1457854914343735550

roles:
  bot: 1457856696394322107
  admin: 1457863864627626209
  moderator: 1457861701302223094
  member: 1457861755429458124
  
log_channels:
  bot: 1457866580020166853
  moderation: 1459319112936456323
